### ISSUE TITLE
e.keyCode will return zero always you should use for firefox e.charCode

### ISSUE THREAD

**Issue by mrr0430** [rwaltenberg/angular-money-mask#1]
example on the events you should use        var keyValue = e.charCode || e.keyCode; to figure out which one is correct. 

element.on('keydown', function (e) {
                var keyValue = e.charCode || e.keyCode;
                if (keyValue === 8) {
                    cents = parseInt(cents.toString().slice(0, -1)) || 0;

                    ngModelCtrl.$setViewValue(cents / 100);
                    ngModelCtrl.$render();
                    scope.$apply();
                    e.preventDefault();
                }
            });

            element.on('keypress',
                function (e) {
                    var keyValue = e.charCode || e.keyCode;
                    var char = String.fromCharCode(keyValue);
                    e.preventDefault();

                    if (char.search(/[0-9\-]/) === 0) {
                        cents = parseInt(cents + char);
                    } else {
                        return false;
                    }

                    ngModelCtrl.$setViewValue(cents / 100);
                    ngModelCtrl.$render();
                    scope.$apply();
                });

**Comment by rwaltenberg** [comment]
Well thought! Care to send a pull request with the fix?
